config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd'

  resources :users, only: [:show,:index,:destroy] do
     member do
        get :following, :followers
     end
  end
  root to: 'static_pages#home'
  get  '/about',   to: 'static_pages#about'
  resources :microposts, only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :followed, class_name: "User"
   validates :follower_id, presence: true
   validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                 dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  VALID_USERNAME_REGEX = /\A[a-z]+\z/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 50 }, uniqueness: true,
                       format: { with: VALID_USERNAME_REGEX }
  def to_param
     username
  end

  def feed
    Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
                        following_ids: following_ids, user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

      def configure_permitted_parameters
          added_attrs = [:name, :username, :email, :password, :password_confirmation, :remember_me]
	  devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
	  devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      end

  def after_sign_in_path_for(resource)
     root_url
  end
  def after_sign_in_path_for(root_path)
     root_url
  end
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:danger] = "You are not authorized to perform this action."
    redirect_to(request.referer||root_path)
  end
  def logged_in_user
     unless user_signed_in?
        flash[:danger] = "Please log in."
        redirect_to new_user_session_path 
      end
  end


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      redirect_to root_url
    end
  end

  def destroy
     @micropost = Micropost.find(params[:id])
     authorize @micropost
     @micropost.destroy
     flash[:success] = "Micropost deleted"
     redirect_to request.referrer || root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user 
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
     if user_signed_in?
        @user = current_user
        @micropost = current_user.microposts.build
	@feed_items = current_user.feed.paginate(page: params[:page])
     end
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :logged_in_user, only: :destroy
  
   def index
      @users = User.paginate(page: params[:page])
   end
   def show
      @user = User.find_by_username(params[:id])
      if user_signed_in? and policy(@user).show? 
        @micropost = current_user.microposts.build 
      end
      @microposts = @user.microposts.paginate(page: params[:page])

   end

   def destroy
      @user = User.find_by_username(params[:id])
      authorize @user 
      User.find_by_username(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
   end

  def following
    @title = "Following"
    @user  = User.find_by_username(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find_by_username(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
   # Returns full title per page
   def full_title(page_title = '')
      base_title = "TOUCH"
      if page_title.empty?
         base_title
      else
         page_title + "|" + base_title
      end
   end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      TOUCH® All rights reserved © 2016 
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Touch", root_path, id: "logo" %>
      <nav>
       <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
	<% if user_signed_in? %>
	  <li><%= link_to "Users", users_path %></li>
	  <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	       <%= current_user.name %><b class="caret"></b>
	    </a>
	    <ul class="dropdown-menu">
	       <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	       <li class="divider"></li>
	       <li>
	         <%= link_to "Log out", destroy_user_session_path, method: :delete %>
	       </li>
	    </ul>
	  </li>
	<% else %>
	  <li><%= link_to "Login", new_user_session_path %></li>
	<% end %>
      </ul>
     </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
       <%= yield %>
       <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if policy(micropost).destroy?  %>
          <%= link_to "delete", micropost, method: :delete,
	                                         data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
      <%= render @feed_items %>
   </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<% if user_signed_in? and policy(@user).show? %>
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>
<h1> About </h1>
<p> TOUCH® social networking site is made as a project in course CS252A @ IITK, in the year 2016. </p>
<em> “Make Applications Great Again” </em>

app/views/static_pages/home.html.erb
 <% if user_signed_in? %>
   <div class="row">
     <aside class="col-md-4">
     <section class="user_info">
        <%= render 'shared/user_info' %>
     </section>
     <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
     </section>
      </aside>
     <div class="col-md-8">
 <h3>Micropost Feed</h3>
          <%= render 'shared/feed' %>
      </div>
    </div>
 <% else %>
 <div class="center jumbotron" id="home">
   <h1>Change is here @ TOUCH</h1>
   <h2>“Make Applications Great Again #MAGA”</h2>
   <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
 </div>
 <% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user==@user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= link_to user.name, user %>
      <% if user_signed_in? and policy(user).destroy? %>
          | <%= link_to "delete", user, method: :delete,
                          data: { confirm: "You sure?" } %>
      <% end %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
     <%= render user %>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
 <aside class="col-md-4">
   <section>
     <h1>
       <%= @user.name %>
     </h1>
   </section>
     <section class="stats">
      <%= render 'shared/stats' %>
   </section>
 </aside>
  <div class="col-md-8">
      <%= render 'follow_form' if user_signed_in? %>
     <% if @user.microposts.any? %>
         <h3>Microposts (<%= @user.microposts.count %>)</h3>
           <ol class="microposts">
           <%= render @microposts %>
           </ol>
	   <%= will_paginate @microposts %>
      <% end %>
      <section class="micropost_form">
           <%= render 'shared/micropost_form' %>
      </section>
   </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
          <li>
               <%= link_to user.name, user %>
	     </li>
       <% end %>
       </ul>

      <%= will_paginate %>
    <% end %>
  </div>
</div>